name: Main

on:
  # Triggers the workflow on push events for the specified branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GCP_PROJECT_ID: prefect-poc-443906
  GCP_PROJECT_NUMBER: 597677810426
  GCP_PROJECT_REGION: us-east1
  GCP_WORKLOAD_IDENTITY_POOL: projects/597677810426/locations/global/workloadIdentityPools/cicd-pool
  GH_REPO: walter-cavinaw/prefect-infra-poc
  

jobs:
  deploy_infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.1"
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "${{ env.GCP_WORKLOAD_IDENTITY_POOL }}/providers/gh-provider"
          service_account: "cicdprocess@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      - name: Apply Terraform
        run: |
          export TF_VAR_gcp_project_id=${{ env.GCP_PROJECT_ID }}
          export TF_VAR_gcp_project_number=${{ env.GCP_PROJECT_NUMBER }}
          export TF_VAR_gcp_project_region=${{ env.GCP_PROJECT_REGION }}
          export TF_VAR_gh_repo=${{ env.GH_REPO }}
          cd infrastructure
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve "tfplan"

  deploy_flows:
    permissions:
      # required to obtain Google Cloud service account credentials
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ env.GCP_WORKLOAD_IDENTITY_POOL }}/providers/gh-provider"
          service_account: "cicdprocess@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
      - id: secrets
        name: "Fetch secrets from Google Cloud"
        uses: "google-github-actions/get-secretmanager-secrets@v2"
        with:
          secrets: |-
            PREFECT_API_KEY:projects/${{ env.GCP_PROJECT_ID }}/secrets/PREFECT_API_KEY
            PREFECT_ACCOUNT_ID:projects/${{ env.GCP_PROJECT_ID }}/secrets/PREFECT_ACCOUNT_ID
            PREFECT_WORKSPACE_ID:projects/${{ env.GCP_PROJECT_ID }}/secrets/PREFECT_WORKSPACE_ID
      - name: Configure Google Cloud credential helper
        run: gcloud auth configure-docker --quiet us-east1-docker.pkg.dev
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run Prefect Deploy
        uses: PrefectHQ/actions-prefect-deploy@v4
        with:
          all-deployments: "true"
          requirements-file-paths: ./requirements.txt
          deployment-file-path: ./prefect.yaml
        env:
          PREFECT_API_KEY: ${{ steps.secrets.outputs.PREFECT_API_KEY }}
          PREFECT_API_URL: "https://api.prefect.cloud/api/accounts/${{ steps.secrets.outputs.PREFECT_ACCOUNT_ID }}/workspaces/${{ steps.secrets.outputs.PREFECT_WORKSPACE_ID }}"
